steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'southamerica-east1-docker.pkg.dev/$PROJECT_ID/hydroponics-repository/hydroponics-metrics-collector:$SHORT_SHA', '.' ]
images:
- 'southamerica-east1-docker.pkg.dev/$PROJECT_ID/hydroponics-repository/hydroponics-metrics-collector:$SHORT_SHA'
