steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', '$_IMAGE_NAME', '.' ]
images:
- '$_IMAGE_NAME'
substitutions:
  # We'll generate the application version being using TAG_NAME or SHORT_SHA
  _GENERATED_APPLICATION_VERSION: ${TAG_NAME:-${SHORT_SHA}}
  # We'll generate an image being tagged either with TAG_NAME
  # if that's present or with SHORT_SHA if no tag is found.
  _IMAGE_NAME: 'southamerica-east1-docker.pkg.dev/hydroponics-392400/hydroponics-repository/hydroponics-metrics-collector:${_GENERATED_APPLICATION_VERSION}'
